config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many_attached :files, service: :amazon
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[ show edit update destroy ]

  # GET /organizations or /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.files.purge
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:title, :endpoint, :access_key, :secret_key, :files)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyCredentials</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization) do |form| %>
  <% if organization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :endpoint, style: "display: block" %>
    <%= form.text_field :endpoint %>
  </div>

  <div>
    <%= form.label :access_key, style: "display: block" %>
    <%= form.text_field :access_key %>
  </div>

  <div>
    <%= form.label :secret_key, style: "display: block" %>
    <%= form.text_field :secret_key %>
  </div>

  <div>
    <%= form.label :files, style: "display: block" %>
    <%= form.file_field :files %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p>
    <strong>Title:</strong>
    <%= organization.title %>
  </p>

  <p>
    <strong>Endpoint:</strong>
    <%= organization.endpoint %>
  </p>

  <p>
    <strong>Access key:</strong>
    <%= organization.access_key %>
  </p>

  <p>
    <strong>Secret key:</strong>
    <%= organization.secret_key %>
  </p>

  <div>
    <strong>File</strong>
    <%= link_to "download file", organization.files.blobs[0].url %>
  </div>

  <p>
    <%= link_to "Show this organization", organization %>
  </p>
</div>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render "form", organization: @organization %>

<br>

<div>
  <%= link_to "Show this organization", @organization %> |
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organizations</h1>

<div id="organizations">
  <%= render @organizations %>
</div>

<%= link_to "New organization", new_organization_path %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form', organization: @organization %>

<br>

<div>
  <%= link_to "Back to organizations", organizations_path %>
</div>

app/views/organizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organization %>

<div>
  <%= link_to "Edit this organization", edit_organization_path(@organization) %> |
  <%= link_to "Back to organizations", organizations_path %>

  <%= button_to "Destroy this organization", organization_path(@organization), method: :delete %>
</div>